Stucation/Controllers/AssessmentController.cs
using Newtonsoft.Json;
using Stucation.Controllers.Utils;
using Stucation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stucation.Controllers
{
    public class AssessmentController : Controller
    {
        // GET: Assessment

        [HttpGet]
        public ActionResult AddAssessment()
        {
            try
            {
                List<ModuleDto> dataList = new List<ModuleDto>();
                ResponseDto res = new FileUtil().ReadFromFile("module");
                if (res.responseCode.Equals("00"))
                {
                    dataList = JsonConvert.DeserializeObject<List<ModuleDto>>(res.responseMessage);
                }

                ViewBag.ModuleList = new ListHelper().ToSelectModuleList(dataList);
            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            return View();
        }

        public ActionResult EditAssessment()
        {
            AssessmentDto dataObj = new AssessmentDto();
            try
            {
                string idHolder = Request.QueryString["i"];
                ResponseDto res = new FileUtil().ReadFromFile("assessment");
                if (res.responseCode.Equals("00"))
                {
                    List<AssessmentDto> dataList = JsonConvert.DeserializeObject<List<AssessmentDto>>(res.responseMessage);
                    dataObj = dataList.Find(p => p.assessmentId == idHolder);
                }
                if (dataObj == null)
                {
                    Response.Redirect("~/Home/index");
                }

            }
            catch(Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            return View(dataObj);
        }
        public ActionResult ViewAssessments()
        {
            List<AssessmentDto> dataList = new List<AssessmentDto>();
            try
            { 
            ResponseDto res = new FileUtil().ReadFromFile("assessment");
            if (res.responseCode.Equals("00"))
            {
                dataList = JsonConvert.DeserializeObject<List<AssessmentDto>>(res.responseMessage);
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            return View(dataList);
        }
        public ActionResult StudentAssessment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitData(AssessmentDto model)
        {
            try
            { 
            //if (ModelState.IsValid)
            {
                model.assessmentId = new ProcessUtil().generateId("ASSESSMENT");
                model.dateCreated = new ProcessUtil().currentPeriod();

                ResponseDto resp = new ResponseDto();
                resp.responseCode = "00";
                resp.responseMessage = "Success";
                List<AssessmentDto> dataList = new List<AssessmentDto>();

                ResponseDto res = new FileUtil().ReadFromFile("assessment");
                if (res.responseCode.Equals("00"))
                {
                    dataList = JsonConvert.DeserializeObject<List<AssessmentDto>>(res.responseMessage);

                    if (dataList.Count > 0)
                    {
                        if (dataList.Find(p => (p.assessmentTitle == model.assessmentTitle)) != null)
                        {
                            resp.responseCode = "01";
                            resp.responseMessage = "Data already exists";

                                new LogUtil().WriteLog("ERROR: " + resp.responseCode);
                                new LogUtil().WriteLog("ERROR: " + resp.responseMessage + " " + model.assessmentTitle);
                            }

                    }
                }

                if (resp.responseCode.Equals("00"))
                {
                    string saveMode = "UPDATE";
                    if (dataList.Count < 1)
                    {
                        saveMode = "APPEND";
                    }
                    dataList.Add(model);

                    new FileUtil().WriteToFile(new ProcessUtil().convertToJson(dataList), "assessment", saveMode);
                    new ProcessUtil().updateSequence("ASSESSMENT", model.moduleId);
                }
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }

            Response.Redirect("~/Home/index");
            return View("~/Home/index");
        }

    }
}

Stucation/Views/Assessment/AddAssessment.cshtml
@{
    ViewBag.Title = "Add Assessment";
}

<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>Add Assessment</h4>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Home/index">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Assessment</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Add Assessment</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Assessment Details</h4>
            </div>
            <div class="card-body">
                @model Stucation.Models.AssessmentDto

                @using (Html.BeginForm("SubmitData", "Assessment", FormMethod.Post))
                {
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label class="form-label">Assessment Title</label>
                            @Html.TextBoxFor(model => model.assessmentTitle, new { placeholder = "Input assessment title", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.assessmentTitle)
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="form-group">
                            <label class="form-label">Score</label>
                            @Html.TextBoxFor(model => model.assessmentTotalScore, new { placeholder = "Input assessment score", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.assessmentTotalScore)
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            <label class="form-label">Assessment Details</label>
                            @Html.TextAreaFor(model => model.assessmentDetail, new { placeholder = "Input assessment details", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.assessmentDetail)
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label class="form-label">Module</label>

                            @Html.DropDownListFor(model => model.moduleId, ViewBag.ModuleList as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.moduleId)
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label class="form-label">Status</label>
                            @Html.DropDownListFor(model => model.status, new SelectList(new[] { "Active", "Inactive" }), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.status)
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label class="form-label">Status</label>
                            @Html.DropDownListFor(model => model.status, new SelectList(new[] { "Active", "Inactive" }), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.status)
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <button type="submit" class="btn btn-primary">submit</button>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>

Stucation/Views/Assessment/EditAssessment.cshtml
@{
    ViewBag.Title = "Edit Assessment";
}

<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>Add Assessment</h4>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Home/index">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Assessment</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Add Assessment</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Assessment Details</h4>
            </div>
            <div class="card-body">
                @model Stucation.Models.AssessmentDto

                @using (Html.BeginForm("SubmitData", "Assessment", FormMethod.Post))
                {
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Assessment ID</label>
                                @Html.TextBoxFor(model => model.assessmentId, new { placeholder = "Input assessment ID", @class = "form-control", @readonly="true" })
                                @Html.ValidationMessageFor(model => model.assessmentId)
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Assessment Title</label>
                                @Html.TextBoxFor(model => model.assessmentTitle, new { placeholder = "Input assessment title", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.assessmentTitle)
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="form-group">
                                <label class="form-label">Score</label>
                                @Html.TextBoxFor(model => model.assessmentTotalScore, new { placeholder = "Input assessment score", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.assessmentTotalScore)
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Assessment Details</label>
                                @Html.TextAreaFor(model => model.assessmentDetail, new { placeholder = "Input assessment details", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.assessmentDetail)
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Module</label>

                                @Html.DropDownListFor(model => model.moduleId, ViewBag.ModuleList as SelectList, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.moduleId)
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Status</label>
                                @Html.DropDownListFor(model => model.status, new SelectList(new[] { "Active", "Inactive" }), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.status)
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Status</label>
                                @Html.DropDownListFor(model => model.status, new SelectList(new[] { "Active", "Inactive" }), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.status)
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <button type="submit" class="btn btn-primary">submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Stucation/Views/Assessment/ViewAssessments.cshtml
@{
    ViewBag.Title = "View Assessments";
}

<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>All Assessments</h4>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Home/index">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Assessment</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">All Assessments</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="row tab-content">
            <div id="list-view" class="tab-pane fade active show col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">All Assessments List  </h4>
                        <a href="~/Assessment/AddAssessment" class="btn btn-primary">+ Add new</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            @model List<Stucation.Models.AssessmentDto>
                            <table id="example3" class="display" style="min-width: 845px">
                                <thead>
                                    <tr>
                                        <th>Assessment ID</th>
                                        <th>Title</th>
                                        <th>Details</th>
                                        <th>Score</th>
                                        <th>Module</th>
                                        <th>Date Created</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var data in Model)
                                    {
                                        <tr>
                                            <td><strong>@data.assessmentId</strong></td>
                                            <td>@data.assessmentTitle</td>
                                            <td>@data.assessmentDetail</td>
                                            <td>@data.assessmentTotalScore</td>
                                            <td>@data.moduleId</td>
                                            <td>@data.dateCreated</td>
                                            <td>
                                                <a href="~/Module/EditAssessment?i=@data.moduleId" class="btn btn-sm btn-primary"><i class="la la-pencil"></i></a>
                                                <a href="javascript:void(0);" class="btn btn-sm btn-danger" style="display:none;"><i class="la la-trash-o"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>