Stucation/Controllers/CourseController.cs
using Newtonsoft.Json;
using Stucation.Controllers.Utils;
using Stucation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Stucation.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult AddCourse()
        {
            return View();
        }
        public ActionResult EditCourse()
        {
            CourseDto dataObj = new CourseDto();
            try
            { 
            string idHolder = Request.QueryString["i"];
            ResponseDto res = new FileUtil().ReadFromFile("course");
            if (res.responseCode.Equals("00"))
            {
                List<CourseDto> dataList = JsonConvert.DeserializeObject<List<CourseDto>>(res.responseMessage);
                dataObj = dataList.Find(p => p.courseId == idHolder);
            }
            if (dataObj == null)
            {
                Response.Redirect("~/Home/index");
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
            }
            return View(dataObj);
        }
        public ActionResult ViewCourses()
        {
            List<CourseDto> dataList = new List<CourseDto>();
            try
            { 
            ResponseDto res = new FileUtil().ReadFromFile("course");
            if (res.responseCode.Equals("00"))
            {
                dataList = JsonConvert.DeserializeObject<List<CourseDto>>(res.responseMessage);
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
            }
            return View(dataList);
        }
        public ActionResult AboutCourse()
        {
            CourseDto dataObj = new CourseDto();
            try
            { 
            string idHolder = Request.QueryString["i"];
            ResponseDto res = new FileUtil().ReadFromFile("course");
            if (res.responseCode.Equals("00"))
            {
                List<CourseDto> dataList = JsonConvert.DeserializeObject<List<CourseDto>>(res.responseMessage);
                dataObj = dataList.Find(p=>p.courseId==idHolder);
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
            }
            return View(dataObj);
        }

        [HttpPost]
        public ActionResult SubmitData(CourseDto model)
        {
            try
            { 
            //if (ModelState.IsValid)
            {
                model.courseId = new ProcessUtil().generateId("COURSE");
                model.dateCreated = new ProcessUtil().currentPeriod();

                ResponseDto resp = new ResponseDto();
                resp.responseCode = "00";
                resp.responseMessage = "Success";
                List<CourseDto> dataList = new List<CourseDto>();

                ResponseDto res = new FileUtil().ReadFromFile("course");
                if (res.responseCode.Equals("00"))
                {
                    dataList = JsonConvert.DeserializeObject<List<CourseDto>>(res.responseMessage);

                    if (dataList.Count > 0)
                    {
                        if(dataList.Find(p => (p.courseName == model.courseName) && (p.coursePeriod == model.coursePeriod)) != null)
                        {
                            resp.responseCode = "01";
                            resp.responseMessage = "Data already exists";

                                new LogUtil().WriteLog("ERROR: " + resp.responseCode);
                                new LogUtil().WriteLog("ERROR: " + resp.responseMessage + " " + model.courseName);
                            }

                    }
                }

                if (resp.responseCode.Equals("00"))
                {
                    string saveMode = "UPDATE";
                    if(dataList.Count < 1)
                    {
                        saveMode = "APPEND";
                    }
                    dataList.Add(model);

                    new FileUtil().WriteToFile(new ProcessUtil().convertToJson(dataList), "course", saveMode);
                    new ProcessUtil().updateSequence("COURSE", model.courseId);
                }
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }

            Response.Redirect("~/Home/index");
            return View("~/Home/index");
        }


        [HttpGet]
        public ActionResult CourseModule()
        {
            List<CourseModuleDto> cmDataList = new List<CourseModuleDto>();
            try
            {
                string idHolder = Request.QueryString["i"];
                CourseDto dataObj = new CourseDto();
                ResponseDto res = new FileUtil().ReadFromFile("course");
                if (res.responseCode.Equals("00"))
                {
                    List<CourseDto> dataLst = JsonConvert.DeserializeObject<List<CourseDto>>(res.responseMessage);
                    dataObj = dataLst.Find(p => p.courseId == idHolder);
                }

                ViewBag.Course = new ListHelper().ToSelectSingleCourseList(dataObj);


                List<ModuleDto> dataList = new List<ModuleDto>();
                res = new FileUtil().ReadFromFile("module");
                if (res.responseCode.Equals("00"))
                {
                    dataList = JsonConvert.DeserializeObject<List<ModuleDto>>(res.responseMessage);
                }

                ViewBag.ModuleList = new ListHelper().ToSelectModuleList(dataList);  


                 res = new FileUtil().ReadFromFile("coursemodule");
                if (res.responseCode.Equals("00"))
                {
                    List<CourseModuleDto> cmDataList1 = JsonConvert.DeserializeObject<List<CourseModuleDto>>(res.responseMessage);
                    cmDataList = cmDataList1.FindAll(p => p.courseId == idHolder);
                }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            var tupleModel = new Tuple<CourseModuleDto, List<CourseModuleDto>>(new CourseModuleDto(), cmDataList);
            return View(tupleModel);
        }

        [HttpPost]
        public ActionResult SubmitCourseModule([Bind(Prefix = "Item1")] CourseModuleDto model)
        {
            try
            {
                //if (ModelState.IsValid)
                {
                    model.courseModuleId = model.courseId + model.moduleId;
                    model.dateCreated = new ProcessUtil().currentPeriod();

                    ResponseDto resp = new ResponseDto();
                    resp.responseCode = "00";
                    resp.responseMessage = "Success";
                    List<CourseModuleDto> dataList = new List<CourseModuleDto>();

                    ResponseDto res = new FileUtil().ReadFromFile("coursemodule");
                    if (res.responseCode.Equals("00"))
                    {
                        dataList = JsonConvert.DeserializeObject<List<CourseModuleDto>>(res.responseMessage);

                        if (dataList.Count > 0)
                        {
                            if (dataList.Find(p => (p.courseId == model.courseId) && (p.moduleId == model.moduleId)) != null)
                            {
                                resp.responseCode = "01";
                                resp.responseMessage = "Data already exists";

                                new LogUtil().WriteLog("ERROR: " + resp.responseCode);
                                new LogUtil().WriteLog("ERROR: " + resp.responseMessage + " " + model.courseModuleId);
                            }

                        }
                    }

                    if (resp.responseCode.Equals("00"))
                    {
                        string saveMode = "UPDATE";
                        if (dataList.Count < 1)
                        {
                            saveMode = "APPEND";
                        }
                        dataList.Add(model);

                        new FileUtil().WriteToFile(new ProcessUtil().convertToJson(dataList), "coursemodule", saveMode);
                    }
                }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            Response.Redirect("~/Home/index");
            return View("~/Home/index");
        }

        public ActionResult ViewCourseModules()
        {
            List<ViewCourseModuleDto> dataList = new List<ViewCourseModuleDto>();
            List<CourseModuleDto> dataList1 = new List<CourseModuleDto>();
            try
            {
                string idHolder = Request.QueryString["i"];

                ResponseDto res = new FileUtil().ReadFromFile("coursemodule");
                if (res.responseCode.Equals("00"))
                {
                    dataList1 = JsonConvert.DeserializeObject<List<CourseModuleDto>>(res.responseMessage);

                    if (dataList1 != null)
                    {
                        foreach (CourseModuleDto dt in dataList1)
                        {
                            ViewCourseModuleDto sm = new ViewCourseModuleDto();
                            sm.courseModule = dt;
                            sm.course = new ProcessUtil().fetchCourseDetails(dt.courseId);
                            sm.module = new ProcessUtil().fetchModuleDetails(dt.moduleId);
                            dataList.Add(sm);
                        }
                    }
                }

                if (idHolder == WebConfigurationManager.AppSettings["adminUser"].ToString())

Stucation/Controllers/LoginController.cs
using Newtonsoft.Json;
using Stucation.Controllers.Utils;
using Stucation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Stucation.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitData(LoginDto model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                }
                else
                {

                    if (model.username.Equals(WebConfigurationManager.AppSettings["adminUser"].ToString()))
                    {
                            Response.Redirect("~/Home/index");
                    }
                    else
                    {

                    }
 
                }
            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
            }
            return View("login");
        }
        
        public ActionResult Logout()
        {
            Response.Redirect("~/Login/login");
            return View();
        }
    }
}

Stucation/Controllers/ModuleController.cs
using Newtonsoft.Json;
using Stucation.Controllers.Utils;
using Stucation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stucation.Controllers
{
    public class ModuleController : Controller
    {
        // GET: Module
        public ActionResult AddModule()
        {
            return View();
        }
        public ActionResult EditModule()
        {
            ModuleDto dataObj = new ModuleDto();
            try
            { 
            string idHolder = Request.QueryString["i"];
            ResponseDto res = new FileUtil().ReadFromFile("module");
            if (res.responseCode.Equals("00"))
            {
                List<ModuleDto> dataList = JsonConvert.DeserializeObject<List<ModuleDto>>(res.responseMessage);
                dataObj = dataList.Find(p => p.moduleId == idHolder);
            }
            if (dataObj == null)
            {
                Response.Redirect("~/Home/index");
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            return View(dataObj);
        }
        public ActionResult ViewModules()
        {
            List<ModuleDto> dataList = new List<ModuleDto>();
            try
            { 
            ResponseDto res = new FileUtil().ReadFromFile("module");
            if (res.responseCode.Equals("00"))
            {
                dataList = JsonConvert.DeserializeObject<List<ModuleDto>>(res.responseMessage);
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            return View(dataList);
        }
        public ActionResult AboutModule()
        {
            ModuleDto dataObj = new ModuleDto();
            try
            { 
            string idHolder = Request.QueryString["i"];
            ResponseDto res = new FileUtil().ReadFromFile("module");
            if (res.responseCode.Equals("00"))
            {
                List<ModuleDto> dataList = JsonConvert.DeserializeObject<List<ModuleDto>>(res.responseMessage);
                dataObj = dataList.Find(p => p.moduleId == idHolder);
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }
            return View(dataObj);
        }

        [HttpPost]
        public ActionResult SubmitData(ModuleDto model)
        {
            try
            { 
            //if (ModelState.IsValid)
            {
                model.moduleId = new ProcessUtil().generateId("MODULE");
                model.dateCreated = new ProcessUtil().currentPeriod();

                ResponseDto resp = new ResponseDto();
                resp.responseCode = "00";
                resp.responseMessage = "Success";
                List<ModuleDto> dataList = new List<ModuleDto>();

                ResponseDto res = new FileUtil().ReadFromFile("module");
                if (res.responseCode.Equals("00"))
                {
                    dataList = JsonConvert.DeserializeObject<List<ModuleDto>>(res.responseMessage);

                    if (dataList.Count > 0)
                    {
                        if (dataList.Find(p => (p.moduleName == model.moduleName)) != null)
                        {
                            resp.responseCode = "01";
                            resp.responseMessage = "Data already exists";

                                new LogUtil().WriteLog("ERROR: " + resp.responseCode);
                                new LogUtil().WriteLog("ERROR: " + resp.responseMessage + " " + model.moduleName);
                            }

                    }
                }

                if (resp.responseCode.Equals("00"))
                {
                    string saveMode = "UPDATE";
                    if (dataList.Count < 1)
                    {
                        saveMode = "APPEND";
                    }
                    dataList.Add(model);

                    new FileUtil().WriteToFile(new ProcessUtil().convertToJson(dataList), "module", saveMode);
                    new ProcessUtil().updateSequence("MODULE", model.moduleId);
                }
            }

            }
            catch (Exception ex)
            {
                new LogUtil().WriteLog("ERROR: " + ex.Message);
                
            }

            Response.Redirect("~/Home/index");
            return View("~/Home/index");
        }
    }
}

Stucation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stucator</title>

    <link rel="icon" type="image/png" sizes="16x16" href="~/images/favicon.png">
    <link rel="stylesheet" href="~/vendor/jqvmap/css/jqvmap.min.css">
    <link rel="stylesheet" href="~/vendor/chartist/css/chartist.min.css">
    <link rel="stylesheet" href="~/vendor/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/skin-2.css">

    <!-- Pick date -->
    <link rel="stylesheet" href="~/vendor/pickadate/themes/default.css">
    <link rel="stylesheet" href="~/vendor/pickadate/themes/default.date.css">

    <link href="~/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
</head>
<body>

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header bg-info">
            <a href="index.html" class="brand-logo">
                <img class="logo-abbr" src="~/images/logo1.png" alt="">
                <img class="logo-compact" src="~/images/logo-text-white.png" alt="">
                <img class="brand-title" src="~/images/logo-text-white.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            
                        </div>

                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <img src="~/images/profile/profile.png" width="20" alt="">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                       @Html.ActionLink("Logout", "Login", "login")
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!--**********************************
            Header end
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="dlabnav">
            <div class="dlabnav-scroll">
                <ul class="metismenu nav nav-list" id="menu">
                    <li class="nav-label first">Main Menu</li>
                    <li>
                        <a class="ai-icon" href="~/Home/index" aria-expanded="false">
                            <i class="la la-home"></i>
                            <span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-users"></i>
                            <span class="nav-text">Student</span>
                        </a>
                        <ul aria-expanded="false">
                            <li>@Html.ActionLink("All Students", "ViewStudents", "Student")</li>
                            <li>@Html.ActionLink("Add Student", "AddStudent", "Student")</li>
                            <li>@Html.ActionLink("View Student Modules", "ViewStudentModules", "Student")</li>
                            <li>@Html.ActionLink("View Student Assessment", "ViewStudentAssessments", "Student")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-graduation-cap"></i>
                            <span class="nav-text">Courses</span>
                        </a>
                        <ul aria-expanded="false">
                            <li>@Html.ActionLink("All Courses", "ViewCourses", "Course")</li>
                            <li>@Html.ActionLink("Add Course", "AddCourse", "Course")</li>
                        </ul>
                    </li>

                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-book"></i>
                            <span class="nav-text">Module</span>
                        </a>
                        <ul aria-expanded="false">
                            <li>@Html.ActionLink("All Modules", "ViewModules", "Module")</li>
                            <li>@Html.ActionLink("Add Module", "AddModule", "Module")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="la la-edit"></i>
                            <span class="nav-text">Assessment</span>
                        </a>
                        <ul aria-expanded="false">
                            <li>@Html.ActionLink("All Assessments", "ViewAssessments", "Assessment")</li>
                            <li>@Html.ActionLink("Add Assessment", "AddAssessment", "Assessment")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            <!-- row -->
            <div class="container-fluid">

                <div class="container body-content">
                    @RenderBody()


                </div>
            </div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p> &copy; @DateTime.Now.Year - Stucator from <a href="christian.enebeli100@gmail.com" target="_blank">christian.enebeli100@gmail.com</a> </p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
        <!--**********************************
           Support ticket button start
        ***********************************-->
        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->
    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="~/vendor/global/global.min.js"></script>
    <script src="~/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/custom.min.js"></script>
    <script src="~/js/dlabnav-init.js"></script>

    <!-- Chart ChartJS plugin files -->
    <script src="~/vendor/chart.js/Chart.bundle.min.js"></script>

    <!-- Chart piety plugin files -->
    <script src="~/vendor/peity/jquery.peity.min.js"></script>

    <!-- Chart sparkline plugin files -->
    <script src="~/vendor/jquery-sparkline/jquery.sparkline.min.js"></script>

    <!-- Demo scripts -->
    <script src="~/js/dashboard/dashboard-3.js"></script>

    <!-- Svganimation scripts -->
    <script src="~/vendor/svganimation/vivus.min.js"></script>
    <script src="~/vendor/svganimation/svg.animation.js"></script>

    <!-- Datatable -->
    <script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/js/plugins-init/datatables.init.js"></script>

    <!-- pickdate -->
    <script src="~/vendor/pickadate/picker.js"></script>
    <script src="~/vendor/pickadate/picker.time.js"></script>
    <script src="~/vendor/pickadate/picker.date.js"></script>

    <!-- Pickdate -->
    <script src="~/js/plugins-init/pickadate-init.js"></script>

</body>
</html>

Stucation/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stucator</title>

    <link rel="icon" type="image/png" sizes="16x16" href="~/images/favicon.png">
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body class="h-100">
    <div class="authincation h-100">
        <div class="container h-100">

            @RenderBody()


        </div>
    </div>


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="~/vendor/global/global.min.js"></script>
    <script src="~/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/custom.min.js"></script>
    <script src="~/js/dlabnav-init.js"></script>

</body>

</html>